# -*- coding: utf-8 -*-
"""GenerativeTextModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xugVBiVjdbzgOEL9WA51Fk9eRxbJHyTV
"""

!pip install transformers

!pip install transformers gradio

import gradio as gr
from transformers import pipeline

generator = pipeline('text-generation', model='gpt2')

def generate_text(prompt):
    try:
        result = generator(prompt, max_length=150, num_return_sequences=1)
        return result[0]['generated_text']
    except Exception as e:
        return str(e)

def ui_function(prompt):
    return generate_text(prompt)

interface = gr.Interface(
    fn=ui_function,
    inputs=gr.Textbox(lines=2, placeholder="Enter your prompt here..."),
    outputs="text",
    title="Generative Text Model (Hugging Face)",
    description="Enter a prompt to generate human-like text using Hugging Face's GPT-2 model.",
    examples=[
        ["Explain the impact of artificial intelligence on healthcare."],
        ["Write a paragraph about the benefits of learning a new language."]
    ]
)

interface.launch()